---
title: "Research"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Interests & Current Research

Broadly, I am interested in renewable energy sources and the interactions between technology and public policy. My current research explores the influence of a biorefinery's location on its financial viability and the environmental impacts of the fuel it produces using techno-economic analysis (TEA) and life cycle assessment (LCA). I have also evaluated the efficacy of existing state-level biofuel tax incentives via TEA and LCA to inform the development of future public policy. You can read this [brief profile](https://cabbi.bio/dalton-stewart-economics-and-environment-both-vital-to-sustainability/) of my work that CABBI published back in 2020, and please refer to my [Google Scholar page](https://scholar.google.com/citations?user=w_vTjaIAAAAJ&hl=en&oi=ao) for the most up to date list of my publications.

$$\\[0.2in]$$

## [Implications of Biorefinery Policy Incentives and Location-Specific Economic Parameters for the Financial Viability of Biofuels](https://pubs.acs.org/doi/10.1021/acs.est.2c07936)

In this paper, my co-authors and I explore the effect of a biorefinery's operating location on its financial viability. To do so, we consider how location-specific economic parameters, like tax rates, electricity prices, and tax incentives, affect a biorefinery's minimum ethanol selling price (MESP, the minimum price at which the biorefinery can afford to sell its fuel). We found that, for cellulosic biorefineries, the MESP is largely driven by capital costs and property taxes. Therefore, further development of the cellulosic biofuel industry could be facilitated by focusing on locations with low property tax rates and/or providing incentives that defray the biorefinery's capital costs. The approach outlined in this study can be extended to other biofuels, feedstocks, and incentives to further inform industrial and policy development.

$$\\[0.2in]$$

## Post-Enactment Evaluation: The Climate and Equitable Jobs Act and Electricity Prices in Illinois

The goal of my research with Senator Bennett's Office was to determine what effect, if any, the Climate and Equitable Jobs Act (CEJA) was having on electricity prices in Illinois. CEJA was enacted in September 2021, and is meant to eliminate greenhouse gas emissions from the energy and transportation sectors in Illinois with an emphasis on an equitable transition. To do so, CEJA contains several provisions that will phase out fossil fuel electricity sources, expand renewable energy generation, and expand economic opportunities for disadvantaged communities and communities affected by the transition away from fossil fuels. CEJA requires Illinois to achieve a 100% zero-emission power sector by 2045, but some critics have suggested that CEJA is responsible for the ongoing (as of January 2023) spike in electricity prices in Illinois. My research during summer 2022 explored the interplay between the specific provisions of CEJA and electricity prices and other global factors influencing electricity prices. I found that spiking electricity prices were due to issues with electricity supply, rather than CEJA. The results of my research were used by the Office of Senator Bennett to communicate with constituents about CEJA’s impacts and the causes of the electricity price spike. Senator Bennett and I worked together to plan legislation to assist low-income residents with their electricity bills.

$$\\[0.2in]$$

## Mapping High-Density Poultry Operations in Southeastern Pennsylvania

As an undergraduate at Bucknell University, I was very fortunate to work with [Dr. Deborah Sills](https://www.bucknell.edu/fac-staff/deborah-sills) on a research project where we investigated the distribution of manure from high-density poultry operations in southeastern Pennsylvania. My job was to contact local County Conservation Districts to get access to manure production records, then record the amounts and locations of manure production at various farms. We collaborated with researchers affiliated with the Geisinger Health System to find that people living closer to such poultry operations were at increased risk of contracting certain illnesses. If you want to read more about this work, please see [Poulsen et al. (2018a)](https://doi.org/10.1097/EE9.0000000000000013) and [Poulsen et al. (2018b)](https://doi.org/10.1016/j.ijheh.2017.12.005).
